FROM pytorch/pytorch:1.13.1-cuda11.3-cudnn8-devel


MAINTAINER nickxu nickxu1001@gmail.com

COPY requirements.txt /home/

RUN pip install -U openmim \
    && mim install mmcv-full==1.5.0 \
    && pip install -r /home/requirements.txt \
    && pip install opencv-python-headless \


ENV APP_PORT=3000 \
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True

EXPOSE $APP_PORT
